### ISSUE TITLE
Help I can't find the .env file.

### ISSUE THREAD

**Issue by MrGlitchWasTaken** [tp-link-extender/MercuryCore#341]
### Describe the bug

I can't find the .env file to put the .env.example in.

### Reproduction

1. uh I just cant find it
2. ?

### Expected behaviour

to easily find the file

### System info

Bun 1.1.27

**Comment by ui0ppk** [comment]
.. you rename the .env.example to .env
???

**Comment by bignegro** [comment]
The .env.example file is in the site directory, you just rename that to .env and that is all you need to do for it

**Comment by MrGlitchWasTaken** [comment]
> .. you rename the .env.example to .env ???

thanks shedletsky

**Comment by ui0ppk** [comment]
you should close the issue now

**Comment by MrGlitchWasTaken** [comment]
> you should close the issue now

how do i get the docker command to work in my terminal

**Comment by bignegro** [comment]
what do you mean?

**Comment by Mantaraix** [comment]
> how do i get the docker command to work in my terminal

please create a separate issue for this
