### ISSUE TITLE
Make giving admin when registering optional

### ISSUE THREAD

**Issue by dxfiscool** [tp-link-extender/MercuryCore#354]
### Describe the problem

By default, when you register you get admin (this also applies to users registered after the first user). There is no clear indication of where to change this.  

### Describe the proposed solution

It would be great for this to be able to be easily toggled in a config file.

**Comment by Heliodex** [comment]
If users registering after the first also receive administrator-level permissions then this isn't intended behaviour, however I wasn't able to recreate this. At the moment there's no user-editable way to change permissions for any account, which there should be an option for in the Admin panel.
Adding an option for this in the config file could work, but probably only if registration keys aren't enabled, as if they are you have to navigate to the admin panel to create one before any new accounts can be registered.

**Comment by ui0ppk** [comment]
you should instead make a cli utility that gives a user admin/mod by id or username

**Comment by dxfiscool** [comment]
> If users registering after the first also receive administrator-level permissions then this isn't intended behaviour, however I wasn't able to recreate this. At the moment there's no user-editable way to change permissions for any account, which there should be an option for in the Admin panel. Adding an option for this in the config file could work, but probably only if registration keys aren't enabled, as if they are you have to navigate to the admin panel to create one before any new accounts can be registered.

I managed to fix this issue.

In the register route, this code is present:
```	const [, , userId] = await equery<string[]>(createUserQuery, {
		username,
		email,
		// I still love scrypt, though argon2 is better supported
		hashedPassword: Bun.password.hashSync(password),
		bodyColours: config.DefaultBodyColors,
		key,
	})
```

I simply replaced it with:
```	const [, , userId] = await equery<string[]>(createUserQuery, {
		admin: false,
		username,
		email,
		// I still love scrypt, though argon2 is better supported
		hashedPassword: Bun.password.hashSync(password),
		bodyColours: config.DefaultBodyColors,
		key,
	})```

	and it worked!

**Comment by Heliodex** [comment]
Well done on the fix, though I'm still unable to recreate the original issue and the change doesn't seem to do anything for me. Do you have any more information on your logs/tool versions/database info?

**Comment by dxfiscool** [comment]
> Well done on the fix, though I'm still unable to recreate the original issue and the change doesn't seem to do anything for me. Do you have any more information on your logs/tool versions/database info?

I'm using Windows 10 Docker Desktop for the database and i'm using WSL 1.0 Ubuntu to host it. Not sure why the same issue isn't present for you. Don't really have any more information than that.
